/**
 * Known-answer (canary) tests for the feed-permission DAG-CBOR wire format.
 *
 * The expected hex and CID values below are generated by the Go implementation and
 * mirrored here, proving byte-identical DAG-CBOR output between TypeScript and Go.
 *
 * Must be kept in sync with
 * pulse-protocol-go/ipfs/cbor_feedpermission_known_test.go.
 */

import type { FeedPermissionPayload } from '@pulse-protocol/types';
import { describe, expect, it } from 'vitest';
import { marshalFeedPermission, unmarshalFeedPermission } from '../cbor-feedpermission.js';
import { getCid } from '../cid.js';

/** Renders bytes as lower-case hex, for comparison with the Go canary values. */
function toHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

/** Fixed 33-byte compressed-key stand-ins — mirror knownNotaryKey1/2 in Go. */
function knownNotaryKey1(): Uint8Array {
  const k = new Uint8Array(33);
  k[0] = 0x02;
  return k;
}
function knownNotaryKey2(): Uint8Array {
  const k = new Uint8Array(33);
  k[0] = 0x03;
  return k;
}

/**
 * v1-shaped feed permission: no dataDescription and a legacy
 * "pulse/feeds/{feedType}/" container path. Mirrors knownV1Payload() in Go.
 */
const knownV1Payload: FeedPermissionPayload = {
  consentNo: 42,
  walletId: 'wlt-canary-v1',
  grantorWebId: 'https://pod.example/alice/profile/card#me',
  counterpartyDid: 'did:web:feeds.example.com',
  feedType: 'open-banking',
  podContainerPath: 'pulse/feeds/open-banking/',
  permissions: ['read', 'write'],
  dataCategories: ['transaction-history', 'account-balance'],
  issuedAt: 1_700_000_000,
  expiresAt: 1_730_000_000,
  encryptedNotary: new Uint8Array([0x01, 0x02, 0x03, 0x04, 0x05]),
  notaryKey1: knownNotaryKey1(),
  notaryKey2: knownNotaryKey2(),
};

// Captured from the Go implementation as it stood before the v2 work (issue #519).
const knownV1Hex =
  'af61746f666565642d7065726d697373696f6e61760162636e182a62646382737472616e73616374696f6e2d686973746f72796f6163636f756e742d62616c616e636562656e4501020304056266746c6f70656e2d62616e6b696e6762706d8264726561646577726974656363706478196469643a7765623a66656564732e6578616d706c652e636f6d636578701a671db480636961741a6553f100636e6b315821020000000000000000000000000000000000000000000000000000000000000000636e6b32582103000000000000000000000000000000000000000000000000000000000000000063706370781970756c73652f66656564732f6f70656e2d62616e6b696e672f637769646d776c742d63616e6172792d76316467776964782968747470733a2f2f706f642e6578616d706c652f616c6963652f70726f66696c652f63617264236d65';
const knownV1Cid = 'bafyreic6ntajpiaijirww2ghopyqyzccffrjv3h5h6r4nsgljiza7rcuia';

describe('feed-permission v1 known answers', () => {
  it('marshals the v1 canary payload to the exact Go bytes', () => {
    expect(toHex(marshalFeedPermission(knownV1Payload))).toBe(knownV1Hex);
  });

  it('produces the CID recorded by the Go implementation', async () => {
    expect(await getCid(marshalFeedPermission(knownV1Payload))).toBe(knownV1Cid);
  });

  it('decodes the stored v1 canary bytes', () => {
    const block = Uint8Array.from(
      (knownV1Hex.match(/../g) ?? []).map((h) => Number.parseInt(h, 16)),
    );
    const got = unmarshalFeedPermission(block);
    expect(got.consentNo).toBe(knownV1Payload.consentNo);
    expect(got.podContainerPath).toBe(knownV1Payload.podContainerPath);
    expect(got.permissions).toEqual(knownV1Payload.permissions);
    expect(got.dataCategories).toEqual(knownV1Payload.dataCategories);
    expect(got.encryptedNotary).toEqual(knownV1Payload.encryptedNotary);
  });
});
